### ISSUE TITLE
base编码问题

### ISSUE THREAD

**Issue by Ca1337** [SUSTech-CRA/qq-add-group-verify#1]
base编码一般用于将不可打印字符编码为可打印字符方便传输，代价是增加长度。  

在SJTU-Plus中，base58的使用目的是将byte格式的时间戳和CMAC编码为可打印字符 https://github.com/SJTU-Plus/sjtu-plus/blob/0c366a18726c7123fc43d21ef9f888bd3183c8bb/verify/utils.py#L31-L35

在本仓库中却是使用base64编码了明文字符，似乎只会增加长度 https://github.com/SUSTech-CRA/qq-add-group-verify/blob/master/app.py#L144-L147 

如果将时间戳转成byte，去掉分隔符 `|` (时间戳位宽固定所以不需要分割)，将MAC转回bytes再用base64编码方可压缩长度   
另外base64本身码表带特殊符号如+/，在QQ传输过程中有概率被转义为表情，使用base58可能更适合QQ验证的场景

**Comment by sparkcyf** [comment]
感谢建议，已参照sjtu的设计使用了base58编码 https://github.com/SUSTech-CRA/qq-add-group-verify/commit/d84981c4e8e8b1836045039f2803995a3dd53ee2
